name: "Jaswinder Singh"
description: "Student, Web buff, Critical Thinking, Music Lover, DIY, Life Hacking, Fortune 500, and 8."

url: "http://jaswinder-singh.github.io/c4c/"
pretty_url: "jaswinder-singh.github.io/c4c/"

# paginate: 10

markdown: kramdown
permalink: /post/:title.html